table Fact_Sales
	lineageTag: ff9b690c-89b6-4e3a-bfdf-7ddb52d8d4c3

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 210baf3d-8b67-4ae1-980d-9f40a0cd951a
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7e98cf25-0240-4252-9241-b2cbac8cfb85
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 5e530386-3d67-4dbe-9e9f-acee40180cf2
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: b54e9ad0-bd7b-4f7a-967e-029f42f10c6e
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 7d6972fc-b1b4-4d10-8a40-01f9f515e000
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: d982d718-0551-4114-bf40-d660e6243055
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: cf6ef65b-a179-4897-aa48-62bb0ac1c91c
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: 0
		lineageTag: ec25816a-51a1-42b9-a2a8-72de071f8de0
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 718fdcab-378a-4428-83d4-7d59854ff5aa
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\A1 1 10.0 1GC 10KT THIRD YEAR\SEM V\A1 10.0 BUSINESS INTELLIGENCE\Lab Mini Project\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", type number}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

